title: bilginotlarım
author: GitHub User
email: admin@bilginotlarim.com
description: > # this means to ignore newlines until "show_exerpts:"
  Yazılım ve bilgi güvenliği üzerine bilgilerimin toplantığı notlar.
show_excerpts: true # set to true to show excerpts on the homepage

paginate: 10
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/bilginotlarim
      icon: twitter-square
      color: cyan
    #- url: https://bitbrain.itch.io
      #icon: itch-io
      #color: red
    #- url: https://github.com/bitbrain
      #icon: github-square
      #color: purple

  show_author: false

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: bitbrain
